apiVersion: v1
kind: Secret
metadata:
  labels:
     {{- include "observatorium.labels" (dict "ctx" $ "component" "api" ) | nindent 4 }}
  name: {{ include "observatorium.resourceName" (dict "ctx" $ "component" "api") }}
stringData:
  tenants.yaml: |-
    "tenants":
    - "id": {{ .Values.api.config.id | quote }}
      "name": {{ .Values.api.config.name | quote }}
      "oidc":
        "clientID": {{ .Values.api.config.clientID | quote }}
        "issuerURL": {{ .Values.api.config.issuerURL | quote }}
        "usernameClaim": {{ .Values.api.config.usernameClaim | quote }}
        {{- if .Values.ingress.enabled }}
        {{- with (first .Values.ingress.hosts) }}
        "redirectURL": "https://{{ .host }}/oidc/infra/callback"
        {{- end }}
        {{- else }}
        "redirectURL": "http://"
        {{- end }}
        "groupClaim": {{ .Values.api.config.groupClaim | quote }}
      {{- if .Values.rate_limiter.enabled }}
      "rateLimits":
      - "endpoint": "/api/metrics/v1/.+/api/v1/receive"
        "limit": 1000
        "window": "1s"
      - "endpoint": "/api/logs/v1/.*"
        "limit": 1000
        "window": "1s"
      {{- end }}
    {{- range $tenant := .Values.tenants }}
    - "id": {{ $tenant.name | quote }}
      "name": {{ $tenant.name | quote }}
      {{- if $tenant.oidc -}}
      "oidc":
        "clientID": {{ $tenant.oidc.clientID | quote }}
        "issuerURL":{{ $tenant.oidc.issuerURL | quote }}
        "usernameClaim": {{ $tenant.oidc.usernameClaim | quote }}
        "redirectURL": {{ $tenant.oidc.redirectURL | quote }}
        "groupClaim": {{ $tenant.oidc.groupClaim | quote }}
      {{- else }}
      "oidc":
        "clientID": {{ $.Values.api.config.clientID | quote }}
        "issuerURL": {{ $.Values.api.config.issuerURL | quote }}
        "usernameClaim": {{ $.Values.api.config.usernameClaim | quote }}
        {{- if $.Values.ingress.enabled }}
        {{- with (first $.Values.ingress.hosts) }}
        "redirectURL": "https://{{ .host }}/oidc/infra/callback"
        {{- end }}
        {{- else }}
        "redirectURL": "http://"
        {{- end }}
        "groupClaim": {{ $.Values.api.config.groupClaim | quote }}
      {{- end }}
      {{- if $.Values.rate_limiter.enabled }}
      "rateLimits":
      - "endpoint": "/api/metrics/v1/.+/api/v1/receive"
        "limit": 1000
        "window": "1s"
      - "endpoint": "/api/logs/v1/.*"
        "limit": 1000
        "window": "1s"
      {{- end }}
    {{- end }}
