apiVersion: v1
kind: ConfigMap
metadata:
  labels:
     {{- include "observatorium.labels" (dict "ctx" $ "component" "api" ) | nindent 4 }}
  name: {{ include "observatorium.resourceName" (dict "ctx" $ "component" "api") }}
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": {{ .Values.api.config.id | quote }}
      "roles":
      - "read-{{ .Values.api.config.id }}"
      "subjects":
      {{- range $group := .Values.api.config.groups }}
      - "kind": "group"
        "name": {{ $group | quote }}
      {{- end }}
    {{- range $tenant := .Values.tenants }}
    - "name": {{ $tenant.name | quote }}
      "roles":
      - "read-{{ $tenant.name }}"
      "subjects":
      {{- range $group := $tenant.groups }}
      - "kind": "group"
        "name": {{ $group | quote }}
      {{- end }}
    {{- end }}
    "roles":
    - "name": "read-{{ .Values.api.config.id }}"
      "permissions":
      - "read"
      "resources":
      - "logs"
      - "metrics"
      - "traces"
      "tenants":
      - {{ .Values.api.config.id }}
    {{- range $tenant := .Values.tenants }}
    - "name": "read-{{ $tenant.name }}"
      "permissions":
      - "read"
      "resources":
      - "logs"
      - "metrics"
      - "traces"
      "tenants":
      - {{ $tenant.name | quote }}
    {{- end }}
