apiVersion: v1
kind: ConfigMap
metadata:
  labels:
     {{- include "observatorium.labels" (dict "ctx" $ "component" "api" ) | nindent 4 }}
  name: {{ include "observatorium.resourceName" (dict "ctx" $ "component" "api") }}
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": {{ .Values.api.config.id | quote }}
      "roles":
      - "read-{{ .Values.api.config.id }}"
      "subjects":
      {{- range $group := .Values.api.config.groups }}
      - "kind": "group"
        "name": {{ $group | quote }}
      {{- end }}
    {{- range $tenant := default .Values.tenants $.Values.global.tenants }}
    {{- if hasKey $tenant "type" }}
    - "name": {{ printf "%s-%s" $tenant.type $tenant.name | quote }}
      "roles":
      - "read-{{ printf "%s-%s" $tenant.type $tenant.name }}"
    {{- else }}
    - "name": {{ $tenant.name | quote }}
      "roles":
      - "read-{{ $tenant.name }}"
    {{- end }}
      "subjects":
      {{- range $group := $tenant.groups }}
      - "kind": "group"
        "name": {{ $group | quote }}
      {{- end }}
    {{- end }}
    "roles":
    - "name": "read-{{ .Values.api.config.id }}"
      "permissions":
      - "read"
      "resources":
      - "logs"
      - "metrics"
      - "traces"
      "tenants":
      - {{ .Values.api.config.id }}
    {{- range $tenant := default .Values.tenants $.Values.global.tenants }}
    {{- if hasKey $tenant "type" }}
    - "name": "read-{{ printf "%s-%s" $tenant.type $tenant.name }}"
    {{- else }}
    - "name": "read-{{ $tenant.name }}"
    {{- end }}
      "permissions":
      - "read"
      "resources":
      - "logs"
      - "metrics"
      - "traces"
      "tenants":
      {{- if hasKey $tenant "type" }}
      - {{ printf "%s-%s" $tenant.type $tenant.name | quote }}
      {{- else }}
      - {{ $tenant.name | quote }}
      {{- end }}
    {{- end }}
